name: Deployment Notification to Discord

on:
  push:
    branches:
      - develop
      - master

jobs:
  notify-discord:
    name: Notify Discord on Push
    runs-on: ubuntu-latest

    steps:
      - name: Wait for deployment
        run: sleep 30 # Vercel 배포 대기

      - name: Notify Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          BRANCH="${{ github.ref_name }}"
          REPO="${{ github.repository }}"
          COMMIT="${{ github.sha }}"
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          AUTHOR="${{ github.event.head_commit.author.name }}"

          # Discord embed 메시지 생성
          JSON_PAYLOAD=$(cat <<EOF
          {
            "embeds": [
              {
                "title": "🚀 배포 시작됨",
                "color": 3447003,
                "fields": [
                  {
                    "name": "브랜치",
                    "value": "$BRANCH",
                    "inline": true
                  },
                  {
                    "name": "저장소",
                    "value": "$REPO",
                    "inline": true
                  },
                  {
                    "name": "작성자",
                    "value": "$AUTHOR",
                    "inline": true
                  },
                  {
                    "name": "커밋 메시지",
                    "value": "$COMMIT_MESSAGE"
                  },
                  {
                    "name": "커밋",
                    "value": "\`${COMMIT:0:7}\`",
                    "inline": true
                  }
                ],
                "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%S.000Z)"
              }
            ]
          }
          EOF
          )

          curl -H "Content-Type: application/json" \
               -d "$JSON_PAYLOAD" \
               $DISCORD_WEBHOOK_URL
